apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  labels:
    app.kubernetes.io/name: django-app
    app.kubernetes.io/instance: web
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 60
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: django-app
              image: etokosmo/django_app:latest
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: django-config
              command: ["python", "./manage.py", "clearsessions"]
          restartPolicy: Never
