apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  labels:
    app.kubernetes.io/name: django-app
    app.kubernetes.io/instance: web
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: django-app
          image: etokosmo/django_app:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: django-config
          command: ["python", "./manage.py", "migrate"]
      restartPolicy: Never